# Generated by Django 5.0.6 on 2024-07-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_cor_options_veiculo"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="acessorio",
            field=models.ManyToManyField(to="core.acessorio"),
        ),
    ]
